import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header/header";
import { ReduxProvider } from "@/redux/provider";

// const inter = Inter({ subsets: ["latin"] });
export const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Meow UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ReduxProvider>
            <Header />
            {children}
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
